name: Linux Build (PyInstaller)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Clean previous builds
        run: |
          rm -rf venv build dist

      - name: Create virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install -U pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generate THIRD_PARTY_NOTICES
        run: |
          source venv/bin/activate
          pip install pip-licenses

          pip-licenses \
            --with-urls \
            --with-license-file \
            --with-notice-file \
            --format=plain-vertical \
            --ignore-packages pip-licenses prettytable wcwidth pip setuptools wheel \
            --output-file THIRD_PARTY_NOTICES.raw.txt

          sed -E '/^\//d' THIRD_PARTY_NOTICES.raw.txt > THIRD_PARTY_NOTICES.txt
          rm -f THIRD_PARTY_NOTICES.raw.txt

      - name: Security audit
        run: |
          source venv/bin/activate
          pip install pip-audit
          pip-audit -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          source venv/bin/activate
          pip install pyinstaller
          pyinstaller --clean --noconfirm --onefile --name "Sentry" run.py
        shell: cmd

      - name: Copy THIRD_PARTY_NOTICES
        run: |
          cp THIRD_PARTY_NOTICES.txt dist/THIRD_PARTY_NOTICES.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Sentry-Linux
          path: |
            dist/Sentry
            dist/THIRD_PARTY_NOTICES.txt
